apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: r3o5lwrle-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/r3o5lwrle-java-quarkus-gitops